<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * ISO 3166-1 alpha-2 country list for the Country field on Company and
 * Customer profiles. A static lookup (like KCRM_Company::payment_types())
 * rather than a DB table -- there's no per-installation customization need.
 */
class KCRM_Countries {

	/** Default country code for a brand-new Company/Customer -- matches the address_country column's DB default. */
	const DEFAULT_CODE = 'US';

	/** @return array<string,string> ISO 3166-1 alpha-2 code => English country name, United States first, then the rest alphabetically. */
	public static function list() {
		static $countries = null;
		if ( null !== $countries ) {
			return $countries;
		}

		$rest = array(
			'AF' => __( 'Afghanistan', 'karks-crm' ),
			'AL' => __( 'Albania', 'karks-crm' ),
			'DZ' => __( 'Algeria', 'karks-crm' ),
			'AS' => __( 'American Samoa', 'karks-crm' ),
			'AD' => __( 'Andorra', 'karks-crm' ),
			'AO' => __( 'Angola', 'karks-crm' ),
			'AI' => __( 'Anguilla', 'karks-crm' ),
			'AQ' => __( 'Antarctica', 'karks-crm' ),
			'AG' => __( 'Antigua and Barbuda', 'karks-crm' ),
			'AR' => __( 'Argentina', 'karks-crm' ),
			'AM' => __( 'Armenia', 'karks-crm' ),
			'AW' => __( 'Aruba', 'karks-crm' ),
			'AU' => __( 'Australia', 'karks-crm' ),
			'AT' => __( 'Austria', 'karks-crm' ),
			'AZ' => __( 'Azerbaijan', 'karks-crm' ),
			'BS' => __( 'Bahamas', 'karks-crm' ),
			'BH' => __( 'Bahrain', 'karks-crm' ),
			'BD' => __( 'Bangladesh', 'karks-crm' ),
			'BB' => __( 'Barbados', 'karks-crm' ),
			'BY' => __( 'Belarus', 'karks-crm' ),
			'BE' => __( 'Belgium', 'karks-crm' ),
			'BZ' => __( 'Belize', 'karks-crm' ),
			'BJ' => __( 'Benin', 'karks-crm' ),
			'BM' => __( 'Bermuda', 'karks-crm' ),
			'BT' => __( 'Bhutan', 'karks-crm' ),
			'BO' => __( 'Bolivia', 'karks-crm' ),
			'BA' => __( 'Bosnia and Herzegovina', 'karks-crm' ),
			'BW' => __( 'Botswana', 'karks-crm' ),
			'BR' => __( 'Brazil', 'karks-crm' ),
			'BN' => __( 'Brunei', 'karks-crm' ),
			'BG' => __( 'Bulgaria', 'karks-crm' ),
			'BF' => __( 'Burkina Faso', 'karks-crm' ),
			'BI' => __( 'Burundi', 'karks-crm' ),
			'KH' => __( 'Cambodia', 'karks-crm' ),
			'CM' => __( 'Cameroon', 'karks-crm' ),
			'CA' => __( 'Canada', 'karks-crm' ),
			'CV' => __( 'Cape Verde', 'karks-crm' ),
			'KY' => __( 'Cayman Islands', 'karks-crm' ),
			'CF' => __( 'Central African Republic', 'karks-crm' ),
			'TD' => __( 'Chad', 'karks-crm' ),
			'CL' => __( 'Chile', 'karks-crm' ),
			'CN' => __( 'China', 'karks-crm' ),
			'CO' => __( 'Colombia', 'karks-crm' ),
			'KM' => __( 'Comoros', 'karks-crm' ),
			'CG' => __( 'Congo', 'karks-crm' ),
			'CD' => __( 'Congo (DRC)', 'karks-crm' ),
			'CK' => __( 'Cook Islands', 'karks-crm' ),
			'CR' => __( 'Costa Rica', 'karks-crm' ),
			'CI' => __( "Cote d'Ivoire", 'karks-crm' ),
			'HR' => __( 'Croatia', 'karks-crm' ),
			'CU' => __( 'Cuba', 'karks-crm' ),
			'CW' => __( 'Curacao', 'karks-crm' ),
			'CY' => __( 'Cyprus', 'karks-crm' ),
			'CZ' => __( 'Czechia', 'karks-crm' ),
			'DK' => __( 'Denmark', 'karks-crm' ),
			'DJ' => __( 'Djibouti', 'karks-crm' ),
			'DM' => __( 'Dominica', 'karks-crm' ),
			'DO' => __( 'Dominican Republic', 'karks-crm' ),
			'EC' => __( 'Ecuador', 'karks-crm' ),
			'EG' => __( 'Egypt', 'karks-crm' ),
			'SV' => __( 'El Salvador', 'karks-crm' ),
			'GQ' => __( 'Equatorial Guinea', 'karks-crm' ),
			'ER' => __( 'Eritrea', 'karks-crm' ),
			'EE' => __( 'Estonia', 'karks-crm' ),
			'SZ' => __( 'Eswatini', 'karks-crm' ),
			'ET' => __( 'Ethiopia', 'karks-crm' ),
			'FK' => __( 'Falkland Islands', 'karks-crm' ),
			'FO' => __( 'Faroe Islands', 'karks-crm' ),
			'FJ' => __( 'Fiji', 'karks-crm' ),
			'FI' => __( 'Finland', 'karks-crm' ),
			'FR' => __( 'France', 'karks-crm' ),
			'GF' => __( 'French Guiana', 'karks-crm' ),
			'PF' => __( 'French Polynesia', 'karks-crm' ),
			'GA' => __( 'Gabon', 'karks-crm' ),
			'GM' => __( 'Gambia', 'karks-crm' ),
			'GE' => __( 'Georgia', 'karks-crm' ),
			'DE' => __( 'Germany', 'karks-crm' ),
			'GH' => __( 'Ghana', 'karks-crm' ),
			'GI' => __( 'Gibraltar', 'karks-crm' ),
			'GR' => __( 'Greece', 'karks-crm' ),
			'GL' => __( 'Greenland', 'karks-crm' ),
			'GD' => __( 'Grenada', 'karks-crm' ),
			'GP' => __( 'Guadeloupe', 'karks-crm' ),
			'GU' => __( 'Guam', 'karks-crm' ),
			'GT' => __( 'Guatemala', 'karks-crm' ),
			'GG' => __( 'Guernsey', 'karks-crm' ),
			'GN' => __( 'Guinea', 'karks-crm' ),
			'GW' => __( 'Guinea-Bissau', 'karks-crm' ),
			'GY' => __( 'Guyana', 'karks-crm' ),
			'HT' => __( 'Haiti', 'karks-crm' ),
			'HN' => __( 'Honduras', 'karks-crm' ),
			'HK' => __( 'Hong Kong', 'karks-crm' ),
			'HU' => __( 'Hungary', 'karks-crm' ),
			'IS' => __( 'Iceland', 'karks-crm' ),
			'IN' => __( 'India', 'karks-crm' ),
			'ID' => __( 'Indonesia', 'karks-crm' ),
			'IR' => __( 'Iran', 'karks-crm' ),
			'IQ' => __( 'Iraq', 'karks-crm' ),
			'IE' => __( 'Ireland', 'karks-crm' ),
			'IM' => __( 'Isle of Man', 'karks-crm' ),
			'IL' => __( 'Israel', 'karks-crm' ),
			'IT' => __( 'Italy', 'karks-crm' ),
			'JM' => __( 'Jamaica', 'karks-crm' ),
			'JP' => __( 'Japan', 'karks-crm' ),
			'JE' => __( 'Jersey', 'karks-crm' ),
			'JO' => __( 'Jordan', 'karks-crm' ),
			'KZ' => __( 'Kazakhstan', 'karks-crm' ),
			'KE' => __( 'Kenya', 'karks-crm' ),
			'KI' => __( 'Kiribati', 'karks-crm' ),
			'KW' => __( 'Kuwait', 'karks-crm' ),
			'KG' => __( 'Kyrgyzstan', 'karks-crm' ),
			'LA' => __( 'Laos', 'karks-crm' ),
			'LV' => __( 'Latvia', 'karks-crm' ),
			'LB' => __( 'Lebanon', 'karks-crm' ),
			'LS' => __( 'Lesotho', 'karks-crm' ),
			'LR' => __( 'Liberia', 'karks-crm' ),
			'LY' => __( 'Libya', 'karks-crm' ),
			'LI' => __( 'Liechtenstein', 'karks-crm' ),
			'LT' => __( 'Lithuania', 'karks-crm' ),
			'LU' => __( 'Luxembourg', 'karks-crm' ),
			'MO' => __( 'Macao', 'karks-crm' ),
			'MG' => __( 'Madagascar', 'karks-crm' ),
			'MW' => __( 'Malawi', 'karks-crm' ),
			'MY' => __( 'Malaysia', 'karks-crm' ),
			'MV' => __( 'Maldives', 'karks-crm' ),
			'ML' => __( 'Mali', 'karks-crm' ),
			'MT' => __( 'Malta', 'karks-crm' ),
			'MH' => __( 'Marshall Islands', 'karks-crm' ),
			'MQ' => __( 'Martinique', 'karks-crm' ),
			'MR' => __( 'Mauritania', 'karks-crm' ),
			'MU' => __( 'Mauritius', 'karks-crm' ),
			'MX' => __( 'Mexico', 'karks-crm' ),
			'FM' => __( 'Micronesia', 'karks-crm' ),
			'MD' => __( 'Moldova', 'karks-crm' ),
			'MC' => __( 'Monaco', 'karks-crm' ),
			'MN' => __( 'Mongolia', 'karks-crm' ),
			'ME' => __( 'Montenegro', 'karks-crm' ),
			'MS' => __( 'Montserrat', 'karks-crm' ),
			'MA' => __( 'Morocco', 'karks-crm' ),
			'MZ' => __( 'Mozambique', 'karks-crm' ),
			'MM' => __( 'Myanmar (Burma)', 'karks-crm' ),
			'NA' => __( 'Namibia', 'karks-crm' ),
			'NR' => __( 'Nauru', 'karks-crm' ),
			'NP' => __( 'Nepal', 'karks-crm' ),
			'NL' => __( 'Netherlands', 'karks-crm' ),
			'NC' => __( 'New Caledonia', 'karks-crm' ),
			'NZ' => __( 'New Zealand', 'karks-crm' ),
			'NI' => __( 'Nicaragua', 'karks-crm' ),
			'NE' => __( 'Niger', 'karks-crm' ),
			'NG' => __( 'Nigeria', 'karks-crm' ),
			'NU' => __( 'Niue', 'karks-crm' ),
			'NF' => __( 'Norfolk Island', 'karks-crm' ),
			'KP' => __( 'North Korea', 'karks-crm' ),
			'MK' => __( 'North Macedonia', 'karks-crm' ),
			'NO' => __( 'Norway', 'karks-crm' ),
			'OM' => __( 'Oman', 'karks-crm' ),
			'PK' => __( 'Pakistan', 'karks-crm' ),
			'PW' => __( 'Palau', 'karks-crm' ),
			'PS' => __( 'Palestine', 'karks-crm' ),
			'PA' => __( 'Panama', 'karks-crm' ),
			'PG' => __( 'Papua New Guinea', 'karks-crm' ),
			'PY' => __( 'Paraguay', 'karks-crm' ),
			'PE' => __( 'Peru', 'karks-crm' ),
			'PH' => __( 'Philippines', 'karks-crm' ),
			'PN' => __( 'Pitcairn', 'karks-crm' ),
			'PL' => __( 'Poland', 'karks-crm' ),
			'PT' => __( 'Portugal', 'karks-crm' ),
			'PR' => __( 'Puerto Rico', 'karks-crm' ),
			'QA' => __( 'Qatar', 'karks-crm' ),
			'RE' => __( 'Reunion', 'karks-crm' ),
			'RO' => __( 'Romania', 'karks-crm' ),
			'RU' => __( 'Russia', 'karks-crm' ),
			'RW' => __( 'Rwanda', 'karks-crm' ),
			'BL' => __( 'Saint Barthelemy', 'karks-crm' ),
			'SH' => __( 'Saint Helena', 'karks-crm' ),
			'KN' => __( 'Saint Kitts and Nevis', 'karks-crm' ),
			'LC' => __( 'Saint Lucia', 'karks-crm' ),
			'MF' => __( 'Saint Martin', 'karks-crm' ),
			'PM' => __( 'Saint Pierre and Miquelon', 'karks-crm' ),
			'VC' => __( 'Saint Vincent and the Grenadines', 'karks-crm' ),
			'WS' => __( 'Samoa', 'karks-crm' ),
			'SM' => __( 'San Marino', 'karks-crm' ),
			'ST' => __( 'Sao Tome and Principe', 'karks-crm' ),
			'SA' => __( 'Saudi Arabia', 'karks-crm' ),
			'SN' => __( 'Senegal', 'karks-crm' ),
			'RS' => __( 'Serbia', 'karks-crm' ),
			'SC' => __( 'Seychelles', 'karks-crm' ),
			'SL' => __( 'Sierra Leone', 'karks-crm' ),
			'SG' => __( 'Singapore', 'karks-crm' ),
			'SX' => __( 'Sint Maarten', 'karks-crm' ),
			'SK' => __( 'Slovakia', 'karks-crm' ),
			'SI' => __( 'Slovenia', 'karks-crm' ),
			'SB' => __( 'Solomon Islands', 'karks-crm' ),
			'SO' => __( 'Somalia', 'karks-crm' ),
			'ZA' => __( 'South Africa', 'karks-crm' ),
			'KR' => __( 'South Korea', 'karks-crm' ),
			'SS' => __( 'South Sudan', 'karks-crm' ),
			'ES' => __( 'Spain', 'karks-crm' ),
			'LK' => __( 'Sri Lanka', 'karks-crm' ),
			'SD' => __( 'Sudan', 'karks-crm' ),
			'SR' => __( 'Suriname', 'karks-crm' ),
			'SE' => __( 'Sweden', 'karks-crm' ),
			'CH' => __( 'Switzerland', 'karks-crm' ),
			'SY' => __( 'Syria', 'karks-crm' ),
			'TW' => __( 'Taiwan', 'karks-crm' ),
			'TJ' => __( 'Tajikistan', 'karks-crm' ),
			'TZ' => __( 'Tanzania', 'karks-crm' ),
			'TH' => __( 'Thailand', 'karks-crm' ),
			'TL' => __( 'Timor-Leste', 'karks-crm' ),
			'TG' => __( 'Togo', 'karks-crm' ),
			'TK' => __( 'Tokelau', 'karks-crm' ),
			'TO' => __( 'Tonga', 'karks-crm' ),
			'TT' => __( 'Trinidad and Tobago', 'karks-crm' ),
			'TN' => __( 'Tunisia', 'karks-crm' ),
			'TR' => __( 'Turkey', 'karks-crm' ),
			'TM' => __( 'Turkmenistan', 'karks-crm' ),
			'TC' => __( 'Turks and Caicos Islands', 'karks-crm' ),
			'TV' => __( 'Tuvalu', 'karks-crm' ),
			'UG' => __( 'Uganda', 'karks-crm' ),
			'UA' => __( 'Ukraine', 'karks-crm' ),
			'AE' => __( 'United Arab Emirates', 'karks-crm' ),
			'GB' => __( 'United Kingdom', 'karks-crm' ),
			'UY' => __( 'Uruguay', 'karks-crm' ),
			'UZ' => __( 'Uzbekistan', 'karks-crm' ),
			'VU' => __( 'Vanuatu', 'karks-crm' ),
			'VA' => __( 'Vatican City', 'karks-crm' ),
			'VE' => __( 'Venezuela', 'karks-crm' ),
			'VN' => __( 'Vietnam', 'karks-crm' ),
			'VG' => __( 'Virgin Islands (British)', 'karks-crm' ),
			'VI' => __( 'Virgin Islands (U.S.)', 'karks-crm' ),
			'WF' => __( 'Wallis and Futuna', 'karks-crm' ),
			'EH' => __( 'Western Sahara', 'karks-crm' ),
			'YE' => __( 'Yemen', 'karks-crm' ),
			'ZM' => __( 'Zambia', 'karks-crm' ),
			'ZW' => __( 'Zimbabwe', 'karks-crm' ),
		);
		asort( $rest );

		$countries = array( self::DEFAULT_CODE => __( 'United States', 'karks-crm' ) ) + $rest;
		return $countries;
	}

	/** @return string The country name for $code, or $code itself if unrecognized. */
	public static function label( $code ) {
		$list = self::list();
		return $list[ $code ] ?? $code;
	}
}
